version: '3.5'
services:
  early_warning:
    image: regfe89/kg_early_warning:latest
    ports:
      - "6969:80"
      - "8001:8001"
    volumes:
      - .conf:/conf
    environment:
      - LOCAL_ADDR=172.22.0.15
    networks:
      network:
        ipv4_address: 172.22.0.15

networks:
  network:
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
