version: '3.5'
services:
  early_warning:
    image: regfe89/kg_early_warning:latest
    ports:
      - "6969:80"
    volumes:
      - conf:/conf
    command: ["telegram-send --config /conf/telegram-send.conf"]

